service:
  port: 8081

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/employeesDB
    username: postgres
    password: admin
    platform: postgres
  jpa:
    hibernate: ddl-auto=update
  batch:
    initialize-schema: always
    job:
      enabled: false