server:
  port: 8781
spring:
  application:
    name: batch
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/employeesDB
    username: postgres
    password: admin
    platform: postgres
  jpa:
    hibernate: ddl-auto=update
  batch:
    initialize-schema: always
    job:
      enabled: false
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 60000
        readTimeout: 10000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1810000